# Generated by Django 2.1.7 on 2019-03-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_favorited_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(blank=True, help_text='Select a category for this book', max_length=100),
        ),
    ]
