# Generated by Django 2.1.7 on 2019-03-13 05:30
from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File
from django.utils.text import slugify

def load_book_data(apps, schema_editor):
    """
    Read a CSV file full of books and insert them into the database.
    """
    Book = apps.get_model('core', 'Book')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'books.csv')
    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:
            print(row, file=open('file.txt', 'w'))
            book_title = row['title']
            # Don't create a book if title matches an existing Book record
            if Book.objects.filter(title=book_title).count():
                continue
            book = Book(
                title = row['title'],
                author = row['author'],
                book_description = row['book_description'],
                book_url = row['book_url'],
                book_category = row['book_category'],
                slug=slugify(row['title'])
            )            
            book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190313_0530'),
    ]

    operations = [migrations.RunPython(load_book_data)]
