# Generated by Django 2.1.7 on 2019-03-13 05:30
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190313_0530'),
    ]

    operations = []
