# Generated by Django 2.1.7 on 2019-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190313_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ManyToManyField(to='core.BookCategory'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a book category (e.g. Django)', max_length=200, null=True),
        ),
    ]
